#!/bin/bash

python yahoo_data.py "^GSPC" "^NDX" "^RUT" "^DJI" SPY DIA IVV IWM UPRO UDOW TQQQ QQQ SSO SPXL SPXS SPXU SQQQ MDY ^VIX VXX UVXY VIXY 
python data_catalog.py "^GSPC" "^NDX" "^RUT" "^DJI" SPY DIA IVV IWM UPRO UDOW TQQQ QQQ SSO SPXL SPXS SPXU SQQQ MDY ^VIX VXX UVXY VIXY


